version: '3.9'

services:
  postgres:
    image: postgres:13.1-alpine
    container_name: diesel.postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: so_searcher_password
      POSTGRES_USER: so_searcher
      POSTGRES_DB: so_searcher
