version: '3.9'

services:
  postgres:
    image: postgres:13.1-alpine
    container_name: diesel.postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: so_searcher_password
      POSTGRES_USER: so_searcher
      POSTGRES_DB: so_searcher

  rust:
    image: rust:1.49-alpine3.11
    container_name: diesel_rust
    restart: always
    volumes:
      - ./:/so_searcher
    depends_on: 
      - postgres

  nginx:
    image: nginx:1.19.6
    ports:
      - "80:80"
    volumes:
      - ./templates:/usr/share/nginx/html
